# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Lumia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'pop'

  target 'LumiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LumiaUITests' do
    # Pods for testing
  end

end
