source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'TRMosaicLayout_Example' do
  pod 'TRMosaicLayout'
  pod 'AFNetworking'

  target 'TRMosaicLayout_Tests' do
    inherit! :search_paths


  end
end
